// Copyright Indigenous: Blood Ritual contributors. MIT licence; see LICENSE.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "BloodRitualTestEnvironment.generated.h"

class UMaterialInterface;
class UBloodRitualDayLightingComponent;
class UStaticMesh;

/**
 * Spawns the minimum scene a map needs to boot and be walked around in: a floor,
 * a directional light, a sky light, a sky atmosphere and a PlayerStart. The sun drives the
 * atmosphere and the sky light captures it, so shadowed sides get daylight.
 *
 * ABloodRitualGameMode creates one of these in InitGame (before any player is spawned)
 * and calls EnsureSceneBasics(). Each piece is only spawned when the world has none,
 * so a hand-made map or the map generated by scripts/editor/create_test_map.py
 * receives no duplicates. The game boots into the empty engine map
 * /Engine/Maps/Entry by default, where all four pieces are missing.
 *
 * The vertical slice (part 1) extends it with EnsureSlicePlaceholders(): a stockpile at
 * the hub next to the PlayerStart, the scavenging containers listed in UBloodRitualSettings
 * at the scavenging area 30 m away, a placeholder noise listener beside them, and camp
 * scenery (a fire pit, a stump, a fallen trunk, rocks, ferns and shrubs) around both, kept
 * off the path between them. The floor uses the CC0 mud ground material and the scenery the
 * CC0 Poly Haven models imported by scripts/editor/import_cc0_assets.py. The attached
 * UBloodRitualDayLightingComponent drives the lights from the day clock.
 *
 * This is bootstrap scaffolding, not a gameplay system: it goes away once a real
 * map ships. Nothing here is replicated.
 */
UCLASS()
class BLOODRITUAL_API ABloodRitualTestEnvironment : public AActor
{
	GENERATED_BODY()

public:
	ABloodRitualTestEnvironment();

	/** Actor tag carried by every floor this class (or create_test_map.py) spawns. */
	static const FName FloorTag;

	/** Actor tag carried by every piece of camp scenery this class spawns. */
	static const FName SceneryTag;

	/** Spawns whichever of the floor, directional light, sky light, sky atmosphere and PlayerStart the world is missing. */
	void EnsureSceneBasics();

	/** Spawns the stockpile, the scavenging containers, the noise listener and the camp scenery when the world has none of each. */
	void EnsureSlicePlaceholders();

	/** Centre of the scavenging area, where the containers are spawned. */
	static FVector GetScavengingAreaLocation();

	/** Where the stockpile stands, beside the PlayerStart. */
	static FVector GetHubStockpileLocation();

private:
	bool HasFloor() const;
	bool HasDirectionalLight() const;
	bool HasSkyLight() const;
	bool HasSkyAtmosphere() const;
	bool HasPlayerStart() const;

	void SpawnFloor();
	void SpawnDirectionalLight();
	void SpawnSkyLight();
	void SpawnSkyAtmosphere();
	void SpawnPlayerStart();

	void SpawnStockpile();
	void SpawnScavengingContainers();
	void SpawnNoiseListener();
	void SpawnCampScenery();

	/**
	 * Spawns a static mesh actor tagged SceneryTag with its bounds centred (horizontally) on
	 * Location; meshes from a Poly Haven set keep their offset inside the set.
	 */
	void SpawnSceneryPiece(UStaticMesh* Mesh, const FVector& Location, float Yaw, float Scale, bool bBlocks);

	/**
	 * /Engine/BasicShapes/Cube, resolved in the constructor so the class default object
	 * hard-references it and the cooker packages it alongside the game.
	 */
	UPROPERTY()
	TObjectPtr<UStaticMesh> FloorMesh;

	/** CC0 ground material (world-aligned tiling mud and leaves); null keeps the cube's default material. */
	UPROPERTY()
	TObjectPtr<UMaterialInterface> FloorMaterial;

	/** Large pieces placed by hand, with collision: fire pit, stump, fallen trunk. */
	UPROPERTY()
	TObjectPtr<UStaticMesh> FirePitMesh;

	UPROPERTY()
	TObjectPtr<UStaticMesh> StumpMesh;

	UPROPERTY()
	TObjectPtr<UStaticMesh> TrunkMesh;

	/** Scattered with collision. */
	UPROPERTY()
	TArray<TObjectPtr<UStaticMesh>> RockMeshes;

	/** Scattered without collision. */
	UPROPERTY()
	TArray<TObjectPtr<UStaticMesh>> PlantMeshes;

	/** Interpolates the spawned (or found) lights between the Day, Dusk and Night settings. */
	UPROPERTY(VisibleAnywhere, Category = "BloodRitual")
	TObjectPtr<UBloodRitualDayLightingComponent> DayLighting;
};
