// Copyright Seminole contributors. MIT licence; see LICENSE.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "SeminoleTestEnvironment.generated.h"

class USeminoleDayLightingComponent;
class UStaticMesh;

/**
 * Spawns the minimum scene a map needs to boot and be walked around in: a floor,
 * a directional light, a sky light and a PlayerStart; then the vertical slice's
 * placeholder actors: the hub stockpile, the scavenging area's supply containers and a
 * noise listener. Its USeminoleDayLightingComponent drives the lights from the day clock.
 *
 * ASeminoleGameMode creates one of these in InitGame (before any player is spawned)
 * and calls EnsureSceneBasics() then EnsureSliceActors(). Each piece is only spawned
 * when the world has none, so a hand-made map or the map generated by
 * scripts/editor/create_test_map.py receives no duplicates. The game boots into the
 * empty engine map /Engine/Maps/Entry by default, where everything is missing.
 *
 * This is bootstrap scaffolding, not a gameplay system: it goes away once a real
 * map ships. Nothing here is replicated.
 */
UCLASS()
class SEMINOLE_API ASeminoleTestEnvironment : public AActor
{
	GENERATED_BODY()

public:
	ASeminoleTestEnvironment();

	/** Actor tag carried by every floor this class (or create_test_map.py) spawns. */
	static const FName FloorTag;

	/** Where the hub stockpile stands, relative to the PlayerStart at the origin. */
	static const FVector HubLocation;
	/** Centre of the scavenging area; containers line up along Y from here. */
	static const FVector ScavengingAreaLocation;

	/** Spawns whichever of the floor, directional light, sky light and PlayerStart the world is missing. */
	void EnsureSceneBasics();

	/**
	 * Spawns the hub stockpile, one supply container per USeminoleSettings::ContainerSupplies
	 * entry at the scavenging area and a placeholder noise listener beside them, each only
	 * when the world has none of that class.
	 */
	void EnsureSliceActors();

private:
	bool HasFloor() const;
	bool HasDirectionalLight() const;
	bool HasSkyLight() const;
	bool HasPlayerStart() const;

	void SpawnFloor();
	void SpawnDirectionalLight();
	void SpawnSkyLight();
	void SpawnPlayerStart();
	void SpawnStockpile();
	void SpawnContainers();
	void SpawnNoiseListener();

	/** Interpolates the sun and sky light between the configured day, dusk and night intensities. */
	UPROPERTY(VisibleAnywhere, Category = "Seminole")
	TObjectPtr<USeminoleDayLightingComponent> DayLighting;

	/**
	 * /Engine/BasicShapes/Cube, resolved in the constructor so the class default object
	 * hard-references it and the cooker packages it alongside the game.
	 */
	UPROPERTY()
	TObjectPtr<UStaticMesh> FloorMesh;
};
