// Copyright Seminole contributors. MIT licence; see LICENSE.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "SeminoleTestEnvironment.generated.h"

class UStaticMesh;

/**
 * Spawns the minimum scene a map needs to boot and be walked around in: a floor,
 * a directional light, a sky light and a PlayerStart.
 *
 * ASeminoleGameMode creates one of these in InitGame (before any player is spawned)
 * and calls EnsureSceneBasics(). Each piece is only spawned when the world has none,
 * so a hand-made map or the map generated by scripts/editor/create_test_map.py
 * receives no duplicates. The game boots into the empty engine map
 * /Engine/Maps/Entry by default, where all four pieces are missing.
 *
 * This is bootstrap scaffolding, not a gameplay system: it goes away once a real
 * map ships. Nothing here is replicated.
 */
UCLASS()
class SEMINOLE_API ASeminoleTestEnvironment : public AActor
{
	GENERATED_BODY()

public:
	ASeminoleTestEnvironment();

	/** Actor tag carried by every floor this class (or create_test_map.py) spawns. */
	static const FName FloorTag;

	/** Spawns whichever of the floor, directional light, sky light and PlayerStart the world is missing. */
	void EnsureSceneBasics();

private:
	bool HasFloor() const;
	bool HasDirectionalLight() const;
	bool HasSkyLight() const;
	bool HasPlayerStart() const;

	void SpawnFloor();
	void SpawnDirectionalLight();
	void SpawnSkyLight();
	void SpawnPlayerStart();

	/**
	 * /Engine/BasicShapes/Cube, resolved in the constructor so the class default object
	 * hard-references it and the cooker packages it alongside the game.
	 */
	UPROPERTY()
	TObjectPtr<UStaticMesh> FloorMesh;
};
